id: P009428
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16731
  title: དག་ཡིག་རྣམས་ཀྱི་ཟུར་འདེབས་ལེགས་བཤད་མཁས་པ་དགྱེས་བྱེད།
  author: ''
  volumes:
    d295d4e9f9b842e483d1c24f75ddc54d:
      image_group_id: I8LS16739
      title: ''
      volume_number: 1
      total_pages: 26
      base_file: v001.txt
